openapi: 3.0.3
info:
  version: 1.0.0
  title: API
  description: API
paths:
  /api/v1/me:
    $ref: "./paths/me/me.yaml#/me"
  /api/v1/auth/login:
    $ref: "./paths/auth/login.yaml#/login"
  /api/v1/auth/register:
    $ref: "./paths/auth/register.yaml#/register"