name: Frontend CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.3'

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Debug SSH key
      run: echo "${{ secrets.EC2_SSH_KEY }}"

    - name: Upload files to EC2
      run: |
        scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no -r ./.next ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/open-school-app

    - name: Deploy on EC2
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/open-school-app
          npm install --production
          pm2 restart all || pm2 start npm --name "open-school-app" -- start
          exit
        EOF